# Generated by Django 5.0.4 on 2024-04-17 09:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('isChronic', models.BooleanField(default=False)),
                ('maladie_type', models.CharField(choices=[('CARDIOVASCULAIRE', 'Maladie cardiovasculaire'), ('RESPIRATOIRE', 'Maladie respiratoire'), ('INFECTIEUSE', 'Maladie infectieuse'), ('AUTOIMMUNE', 'Maladie auto-immune'), ('MENTALE', 'Maladie mentale'), ('GENETIQUE', 'Maladie génétique'), ('CANCER', 'Cancer'), ('METABOLIQUE', 'Trouble métabolique'), ('NEUROLOGIQUE', 'Trouble neurologique'), ('AUTRE', 'Autre')], max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Hosptial', 'verbose_name_plural': 'Hospitals'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.CreateModel(
            name='Ordonance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='api.doctor')),
                ('maladie', models.ManyToManyField(related_name='maladies', to='api.maladie')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonances', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ratio', models.IntegerField(default=1)),
                ('duree', models.IntegerField(default=7)),
                ('notes', models.TextField(blank=True, null=True)),
                ('isChronic', models.BooleanField(default=False)),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medicament')),
                ('ordonance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='api.ordonance')),
            ],
        ),
    ]
