# Generated by Django 5.0.4 on 2024-04-20 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_maladie_medicament_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonance',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='api.doctor'),
        ),
    ]
