# Generated by Django 5.0.4 on 2024-06-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patient_carte_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='maladies',
        ),
        migrations.CreateModel(
            name='MaladieP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiche', models.BooleanField(default=True)),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maladie')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maladies', to='api.patient')),
            ],
        ),
        migrations.AlterField(
            model_name='consultation',
            name='maladie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maladies', to='api.maladiep'),
        ),
    ]
