# Generated by Django 5.0.4 on 2024-04-20 11:22

import api.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ordonance_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labo',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('labo_address', models.CharField(blank=True, max_length=100, null=True)),
                ('labo_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Labo',
                'verbose_name_plural': 'Labos',
            },
            bases=('api.profile',),
            managers=[
                ('objects', api.managers.ProfileManager()),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='api.hospital'),
        ),
    ]
