# Generated by Django 5.0.4 on 2024-06-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_patient_maladies_maladiep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='maladie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maladies', to='api.maladiep'),
        ),
        migrations.AlterField(
            model_name='maladiep',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maladies', to='api.patient'),
        ),
    ]
