# Generated by Django 5.0.4 on 2024-04-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_labo_doctor_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='maladies',
            field=models.ManyToManyField(blank=True, null=True, to='api.maladie'),
        ),
    ]
