# Generated by Django 5.0.4 on 2024-06-02 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_consultation_maladie_alter_maladiep_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='maladie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='api.maladiep'),
        ),
    ]
