# Generated by Django 5.0.4 on 2024-06-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_consultation_maladie'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='etat_carte',
            field=models.IntegerField(default=0),
        ),
    ]
