# Generated by Django 5.0.4 on 2024-04-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_patient_maladies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='emergency_numbers',
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='api.hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='maladies',
            field=models.ManyToManyField(blank=True, to='api.maladie'),
        ),
    ]
