# Generated by Django 5.0.4 on 2024-05-05 06:09

import api.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospitals',
        ),
        migrations.RenameField(
            model_name='medicamentdetails',
            old_name='ratio',
            new_name='qte',
        ),
        migrations.RemoveField(
            model_name='medicamentdetails',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ordonance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ordonance',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='ordonance',
            name='maladie',
        ),
        migrations.RemoveField(
            model_name='ordonance',
            name='patient',
        ),
        migrations.AddField(
            model_name='doctor',
            name='certeficat',
            field=models.ImageField(blank=True, null=True, upload_to='certeficats/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labo',
            name='certeficat',
            field=models.ImageField(blank=True, null=True, upload_to='certeficats/'),
        ),
        migrations.AddField(
            model_name='labo',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordonance',
            name='analyse',
            field=models.CharField(blank=True, choices=[('HEMATOLOGIE', 'Hématologie'), ('BIOCHIMIE', 'Biochimie'), ('MICROBIOLOGIE', 'Microbiologie'), ('IMMUNOLOGIE', 'Immunologie'), ('GENETIQUE', 'Génétique'), ('RADIOLOGIE', 'Radiologie'), ('ANATOMOPATHOLOGIE', 'Anatomopathologie'), ('CYTOLOGIE', 'Cytologie'), ('VIROLOGIE', 'Virologie'), ('PARASITOLOGIE', 'Parasitologie'), ('TOXICOLOGIE', 'Toxicologie')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordonance',
            name='operation',
            field=models.CharField(blank=True, choices=[('CHIRURGIE_CARDIAQUE', 'Chirurgie cardiaque'), ('CHIRURGIE_ORTHOPEDIQUE', 'Chirurgie orthopédique'), ('CHIRURGIE_ESTHETIQUE', 'Chirurgie esthétique'), ('CHIRURGIE_DIGESTIVE', 'Chirurgie digestive'), ('CHIRURGIE_VASCULAIRE', 'Chirurgie vasculaire'), ('CHIRURGIE_NEUROLOGIQUE', 'Chirurgie neurologique'), ('CHIRURGIE_UROLOGIQUE', 'Chirurgie urologique'), ('CHIRURGIE_GYNECOLOGIQUE', 'Chirurgie gynécologique'), ('CHIRURGIE_THORACIQUE', 'Chirurgie thoracique'), ('CHIRURGIE_OPHTALMOLOGIQUE', 'Chirurgie ophtalmologique'), ('AUTRE', 'Autre')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordonance',
            name='radio',
            field=models.CharField(blank=True, choices=[('RADIOGRAPHIE', 'Radiographie'), ('SCAN', 'Tomodensitométrie (TDM)'), ('IRM', 'Imagerie par Résonance Magnétique (IRM)'), ('TEP', 'Tomographie par Émission de Positons (TEP)'), ('ÉCHOGRAPHIE', 'Échographie'), ('MAMMOGRAPHIE', 'Mammographie'), ('FLUOROSCOPIE', 'Fluoroscopie'), ('MÉDECINE_NUCLÉAIRE', 'Imagerie en Médecine Nucléaire'), ('AUTRE', 'Autre')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nbr_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordonance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default=api.models.generate_short_id, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.doctor')),
                ('maladie', models.ManyToManyField(related_name='maladies', to='api.maladie')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.patient')),
            ],
        ),
        migrations.AddField(
            model_name='ordonance',
            name='consultaion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonances', to='api.consultation'),
        ),
        migrations.CreateModel(
            name='DocumentMedicale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('labo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.labo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
