# Generated by Django 5.0.4 on 2024-05-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_doctor_hospitals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
