# Generated by Django 5.0.4 on 2024-05-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_patient_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labo',
            name='labo_address',
        ),
        migrations.AddField(
            model_name='documentmedicale',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
