# Generated by Django 5.0.4 on 2024-05-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_labo_labo_address_documentmedicale_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmedicale',
            name='document',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
