# Generated by Django 5.0.4 on 2024-05-06 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_documentmedicale_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonance',
            name='analyse',
        ),
        migrations.RemoveField(
            model_name='ordonance',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='ordonance',
            name='radio',
        ),
        migrations.AddField(
            model_name='documentmedicale',
            name='demande',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentmedicale',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.doctor'),
        ),
        migrations.AddField(
            model_name='documentmedicale',
            name='type_doc',
            field=models.CharField(blank=True, choices=[('RADIOGRAPHIE', 'Radiographie'), ('SCAN', 'Tomodensitométrie (TDM)'), ('IRM', 'Imagerie par Résonance Magnétique (IRM)'), ('TEP', 'Tomographie par Émission de Positons (TEP)'), ('ÉCHOGRAPHIE', 'Échographie'), ('MAMMOGRAPHIE', 'Mammographie'), ('FLUOROSCOPIE', 'Fluoroscopie'), ('MÉDECINE_NUCLÉAIRE', 'Imagerie en Médecine Nucléaire'), ('AUTRE', 'Autre')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordonance',
            name='analyses',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='ordonance',
            name='radios',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='documentmedicale',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documentmedicale',
            name='labo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.labo'),
        ),
    ]
