# Generated by Django 5.0.4 on 2024-05-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_ordonance_analyse_remove_ordonance_operation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('radio_type', models.CharField(max_length=50)),
                ('radio_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordonance',
            name='analyses',
        ),
        migrations.RemoveField(
            model_name='ordonance',
            name='radios',
        ),
        migrations.AddField(
            model_name='ordonance',
            name='analyses',
            field=models.ManyToManyField(related_name='analyses', to='api.analyse'),
        ),
        migrations.AddField(
            model_name='ordonance',
            name='radios',
            field=models.ManyToManyField(related_name='radios', to='api.radio'),
        ),
    ]
