# Generated by Django 5.0.4 on 2024-05-06 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_analyse_radio_remove_ordonance_analyses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonance',
            name='analyses',
        ),
        migrations.RemoveField(
            model_name='ordonance',
            name='radios',
        ),
        migrations.RemoveField(
            model_name='documentmedicale',
            name='type_doc',
        ),
        migrations.AddField(
            model_name='documentmedicale',
            name='ordonance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.ordonance'),
        ),
        migrations.AddField(
            model_name='documentmedicale',
            name='radio_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentmedicale',
            name='radio_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordonance',
            name='consultaion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonance', to='api.consultation'),
        ),
        migrations.DeleteModel(
            name='Analyse',
        ),
        migrations.DeleteModel(
            name='Radio',
        ),
    ]
