# Generated by Django 5.0.4 on 2024-05-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_ordonance_analyses_remove_ordonance_radios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmedicale',
            name='type_doc',
            field=models.IntegerField(default=1),
        ),
    ]
