# Generated by Django 5.0.4 on 2024-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_documentmedicale_type_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmedicale',
            name='type_doc',
            field=models.CharField(default='R', max_length=5),
        ),
    ]
