# Generated by Django 5.0.4 on 2024-05-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_maladie_allergie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmedicale',
            name='ordonance',
        ),
    ]
