# Generated by Django 5.0.4 on 2024-05-27 18:19

import api.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_patient_married'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='married',
            field=models.CharField(blank=True, choices=[('Célibataire', 'CELIBATAIRE'), ('Marié(e)', 'MARIE'), ('Divorcé(e)', 'DIVORCE'), ('Veuf/Veuve', 'VEUF')], default=api.enums.SituationMatrimoniale['CELIBATAIRE'], max_length=20, null=True),
        ),
    ]
