# Generated by Django 5.0.4 on 2024-05-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_allergie_remove_maladie_allergie_patient_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergie',
            name='affiche',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='allergie',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
