# Generated by Django 5.0.4 on 2024-05-28 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_allergie_affiche_alter_allergie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='maladie',
        ),
        migrations.AddField(
            model_name='consultation',
            name='maladie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maladies', to='api.maladie'),
        ),
    ]
