# Generated by Django 5.0.4 on 2024-05-28 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_consultation_maladie_consultation_maladie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='maladie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maladies', to='api.maladie'),
        ),
    ]
