# Generated by Django 5.0.4 on 2024-05-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_consultation_maladie'),
    ]

    operations = [
        migrations.AddField(
            model_name='maladie',
            name='membre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
