# Generated by Django 5.0.4 on 2024-05-28 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_maladie_membre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maladie',
            name='membre',
        ),
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membre', models.CharField(blank=True, max_length=50, null=True)),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecs', to='api.maladie')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecs', to='api.patient')),
            ],
        ),
    ]
