# Generated by Django 5.0.4 on 2024-05-30 10:56

import api.managers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_delete_antecedent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('labo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.labo')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('api.labo',),
            managers=[
                ('objects', api.managers.ProfileManager()),
            ],
        ),
    ]
