# Generated by Django 5.0.4 on 2024-05-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_patient_antecedents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Antecedent',
        ),
    ]
