# Generated by Django 5.0.4 on 2024-05-30 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_delete_antecedent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('membre', models.CharField(blank=True, max_length=100, null=True)),
                ('cateogry', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='antecedents',
            field=models.ManyToManyField(blank=True, related_name='antecedents', to='api.antecedent'),
        ),
    ]
