# Generated by Django 5.0.4 on 2024-05-30 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_antecedent_alter_patient_antecedents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmedicale',
            name='labo',
        ),
        migrations.AlterField(
            model_name='documentmedicale',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_as_medic', to=settings.AUTH_USER_MODEL),
        ),
    ]
