# Generated by Django 5.0.4 on 2024-06-01 16:13

import api.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_documentmedicale_labo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='labo_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialite',
            field=models.CharField(choices=[('Cardiologie', 'CARDIOLOGIE'), ('Dermatologie', 'DERMATOLOGIE'), ('Gastro-entérologie', 'GASTRO_ENTEROLOGIE'), ('Neurologie', 'NEUROLOGIE'), ('Pédiatrie', 'PEDIATRIE'), ('Psychiatrie', 'PSYCHIATRIE'), ('Radiologie', 'RADIOLOGIE'), ('Chirurgie', 'CHIRURGIE'), ('Autre', 'AUTRE')], default=api.enums.Specialite['AUTRE'], max_length=50),
        ),
    ]
